import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${notoSansJP.variable}`}
      >
        <div className="flex min-h-screen flex-col">
          <Navbar />
          <div className="mx-auto w-full max-w-5xl flex-1 px-4 py-6">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
